### ISSUE TITLE
Milk-V Duo Support?

### ISSUE THREAD

**Issue by robtech21** [NickCao/nixos-riscv#10]
Lately I've been working with the [Milk-V Duo](https://milkv.io/duo), which is a low-cost Pico-sized SBC with some solid capabilities. The [current build system](https://github.com/milkv-duo/duo-buildroot-sdk/) uses Buildroot as well as some other tools to build a custom image. The only real problem with this system is it's only effective if you clean out the repository and clone it again. Do you think that it would be feasible and more effective to port NixOS to the Duo as opposed to using the Buildroot system?

**Comment by NickCao** [comment]
Porting NixOS to new boards are normally not that hard, mostly figuring out the bootloader part (and you may just use the prebuilt ones for the initial testing). And thank you for reminding me these cheap boards exists! I'm gonna buy some now.

**Comment by NickCao** [comment]
I checked the documents at https://github.com/milkv-duo/duo-buildroot-sdk, looks like the board does not have mainline uboot and kernel support? That would be a concern in the long run.

**Comment by robtech21** [comment]
> I checked the documents at https://github.com/milkv-duo/duo-buildroot-sdk, looks like the board does not have mainline uboot and kernel support? That would be a concern in the long run.

I see. Maybe submit an issue and see if they'll add mainline support? The project is still sort of in its infancy with major quality of life changes (Python+Pip, swap on by default, etc.) only having occurred recently.

**Comment by NickCao** [comment]
> I see. Maybe submit an issue and see if they'll add mainline support?

That would require enormous amount of efforts that a hardware company may or may not want to invest, hope the community would give a helping hand though.

**Comment by robtech21** [comment]
Ah, maybe that will be the case hopefully. For the time being though, Nix is feasible on this?

**Comment by NickCao** [comment]
> Ah, maybe that will be the case hopefully. For the time being though, Nix is feasible on this?

IMO, yes. Still it needs some effort to fit NixOS into that 64MB of ram.

**Comment by robtech21** [comment]
> Still it needs some effort to fit NixOS into that 64MB of ram.

I was a bit surprised by this, until I checked the system requirements for NixOS on X86. It would make sense how something like NixOS might need more RAM as opposed to something more minimal like Buildroot.

**Comment by NickCao** [comment]
Good news! https://www.phoronix.com/news/Milk-V-Duo-Linux-Patches

**Comment by robtech21** [comment]
> Good news! https://www.phoronix.com/news/Milk-V-Duo-Linux-Patches

Awesome!

**Comment by NickCao** [comment]
And my milkv duo is on the way, bought four of them and two IO boards.

**Comment by robtech21** [comment]
> And my milkv duo is on the way, bought four of them and two IO boards.

Very cool. I might get an IO board and an extra Duo for messing around with, I wish the official one broke out the GPIO.

Someone on the forums has a custom-made IO board that has an on-board USB WiFi chip, but it's basically unavailable to me in NA since the website is Chinese.

**Comment by robtech21** [comment]
> And my milkv duo is on the way, bought four of them and two IO boards.

@NickCao Have you started on development yet? I have my Duo and IOB in so I can help test.

**Comment by NickCao** [comment]
Haven't had the time to setup them up, would begin porting during the winter break.

**Comment by robtech21** [comment]
Gotcha, just be sure to post your results in the [Milk-V forums](https://community.milkv.io/) once you get it working. Also, they have a new 256mb RAM version [on pre-order](https://arace.tech/products/milk-v-duo?variant=42525052534964) currently. :)

**Comment by NickCao** [comment]
> Gotcha, just be sure to post your results in the [Milk-V forums](https://community.milkv.io/) once you get it working. 

Sure, I will first try to boot the official SDK userland with NixOS built kernel.

> Also, they have a new 256mb RAM version [on pre-order](https://arace.tech/products/milk-v-duo?variant=42525052534964) currently. :)

That looks promising!

**Comment by robtech21** [comment]
Best of luck!

**Comment by NickCao** [comment]
Progress report: the `boot.sd` built on https://github.com/NickCao/nixos-riscv/commit/6b2c4fa44ac30156deb266b94d758bfad1760899 can now successfully boot the vendor sdk image.

**Comment by NickCao** [comment]
I think the next step is try to enable vector and thead riscv extension, before working on uboot.

**Comment by robtech21** [comment]
I saw the commit when checking the other day. Send a message here if you need me to test it.

**Comment by NickCao** [comment]
![screenshot-2023-12-30-22-21-59](https://github.com/NickCao/nixos-riscv/assets/15247171/cc82430a-e8d6-4356-9d88-3974e5cc0b13)
Booting to the login prompt! Did use some hack to skip the initrd, and we are on the verge of oom.

**Comment by NickCao** [comment]
On current master, the full 64M of memory is available to use, I consider milkv duo support to be complete. The latest sdcard image can be found at https://hydra.nichi.co/job/nixos/riscv/duo/latest/
