### ISSUE TITLE
Changing boot.kernelParams seems to have no effect on duo

### ISSUE THREAD

**Issue by mcdonc** [NickCao/nixos-riscv#12]
Hi Nick,

I'm trying to bring up the new-ish Milk V Duo 256M board (https://github.com/mcdonc/nixos-riscv/tree/duo-256), and I've got it booting up to this point:

```
starting device mapper and LVM...
[    3.428080] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] loadkmap: can't open console
[    3.437372] random: lvm: uninitialized urandom read (4 bytes read)
[    3.455223] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] starting device mapper and LVM...
  Failed to set up async io, using sync io.
[    3.481599] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] Failed to set up async io, using sync io.
checking /dev/disk/by-label/NIXOS_SD...
fsck (busybox 1.36.1)
[fsck.ext4 (1) -- /mnt-root/] [    3.586874] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] checking /dev/disk/by-label/NIXOS_SD...
fsck.ext4 -a /dev/disk/by-label/NIXOS_SD
[    3.614804] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] fsck (busybox 1.36.1)
NIXOS_SD: recovering journal
[    3.629519] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] [fsck.ext4 (1) -- /mnt-root/] fsck.ext4 -a /dev/disk/by-label/NIXOS_SD
[    3.649845] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] NIXOS_SD: recovering journal
NIXOS_SD: clean, 47600/59904 files, 223233/231966 blocks
[    3.676827] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] NIXOS_SD: clean, 47600/59904 files, 223233/231966 blocks
mounting /dev/disk/by-label/NIXOS_SD on /...
[    3.706598] stage-1-init: [Thu Jan  1 00:00:03 UTC 1970] mounting /dev/disk/by-label/NIXOS_SD on /...
[    3.721891] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    3.735810] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
stage 2 init script (/mnt-root//init) not found

An error occurred in stage 1 of the boot process, which must mount the
root filesystem on `/mnt-root' and then start stage 2.  Press one
of the following keys:

  r) to reboot immediately
  *) to ignore the error and continue
```

I'd like to add various kernel flags to do some debugging, but changing `boot.kernelParams` of my duo-256.nix (a copy of your duo.nix with various changes to support the 256) seems to have no effect.  I always end up with this set of flags passed down to the kernel:

Kernel command line: root=/dev/mmcblk0p2 rootwait rw console=ttyS0,115200 earlycon=sbi riscv.fwsz=0x80000 loglevel=9

These *seem* like they'd be coming from kernelParams, but adding one does not change the command line reported by the kernel.

I've generated an appropriate .dts for the board by running the buildroot, but the flags aren't in there or the associated .dtb either.

I'm a U-Boot noob I fear.  Is there a way to add flags manually in the U-Boot CLI maybe for only the current boot?

**Comment by mcdonc** [comment]
Figured out the way to add flags (in this case, boot.shell_on_fail) per-boot is to do this is the U-Boot CLI

```
setenv othbootargs earlycon=sbi riscv.fwsz=0x80000 loglevel=9 boot.shell_on_fail=1
```

then ``boot``.

Didn't get a chance to run a shell after that, but that's a separate problem :)

**Comment by NickCao** [comment]
> These _seem_ like they'd be coming from kernelParams, but adding one does not change the command line reported by the kernel.

Well actually they are not, I should have made this clear in comments. Due to the strange boot setup of duo around its images, there's no easy way of injecting kernel params apart from adding dtb overlays, which, I've yet to figure out how.
