### ISSUE TITLE
VisionFive 2: cannot boot with latest image

### ISSUE THREAD

**Issue by SeTSeR** [NickCao/nixos-riscv#22]
Hello! Today I tried to flash your latest image on my VisionFive 2, but I’m getting weird errors on boot:
Can't set block device
Importing environment from mmc1 ...
## Error: "boot2" not defined
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:3...
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Card did not respond to voltage select! : -110
No EFI system partition
ethernet@16030000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
phy_startup() failed: -110FAILED: -110ethernet@16040000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
phy_startup() failed: -110FAILED: -110ethernet@16030000 Waiting for PHY auto negotiation to complete......... TIMEOUT !

I don’t have an Ethernet connection for this board, as I use wireless network. I tried to boot directly from mmc using boot_mmc0, but that also failed. I see this line:
libfdt fdt_check_header(): FDT_ERR_BADMAGIC

Does it mean that current image is broken?

**Comment by NickCao** [comment]
> Importing environment from mmc1

Sounds like something wrong with the u-boot copy on the on board flash chip. Could you try setting the boot mode to SDIO following section 4.5. VisionFive 2 Boot Mode Settings in the quick start guide: https://doc-en.rvspace.org/VisionFive2/PDF/VisionFive2_QSG.pdf

**Comment by SeTSeR** [comment]
> > Importing environment from mmc1
> 
> Sounds like something wrong with the u-boot copy on the on board flash chip. Could you try setting the boot mode to SDIO following section 4.5. VisionFive 2 Boot Mode Settings in the quick start guide: https://doc-en.rvspace.org/VisionFive2/PDF/VisionFive2_QSG.pdf

Still fails to boot:
```
Working FDT set to ff72c9b0
Hit any key to stop autoboot:  0 
Card did not respond to voltage select! : -110
No EFI system partition
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
No EFI system partition
Failed to persist EFI variables
** Booting bootflow '<NULL>' with efi_mgr
Loading Boot0000 'mmc 1' failed
Loading Boot0001 'nvme 0' failed
EFI boot manager: Cannot load any image
Boot failed (err=-14)
Card did not respond to voltage select! : -110
ethernet@16030000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
phy_startup() failed: -110
FAILED: -110
ethernet@16040000 Waiting for PHY auto negotiation to complete......... TIMEOUT !
phy_startup() failed: -110
FAILED: -110
```
Maybe I incorrectly flashed the image?

For the record: my board is V1.2A

**Comment by NickCao** [comment]
> Card did not respond to voltage select! : -110

Do you have a sdcard inserted or not? I meant try booting from an image flashed onto sdcard.

**Comment by SeTSeR** [comment]
> > Card did not respond to voltage select! : -110
> 
> 
> 
> Do you have a sdcard inserted or not? I meant try booting from an image flashed onto sdcard.

Yes, sdcard is inserted, re-plugged it and re-checked, the problem is still the same. Card itself should be operational, as machine booted from it before.

**Comment by NickCao** [comment]
Then I have zero idea, there must be some particularities with the v1.2A boards since the image do work with v1.3B boards.

**Comment by SeTSeR** [comment]
It seems the problem was indeed in incorrectly written media, I rewritten image on sd card a couple of times, and the system booted successfully.
