### ISSUE TITLE
Ethernet isn't working (vf2)

### ISSUE THREAD

**Issue by kangaroo** [NickCao/nixos-riscv#3]
hey @NickCao -- I've been checking out your work, and I can see end0 and end1 come up, but I'm not getting any connectivity.  known issue?

**Comment by NickCao** [comment]
Yes, this is a known issue. The ethernet is not exactly non working, packets do get through occasionally, but indeed not fully functional.

**Comment by kangaroo** [comment]
I'm not really getting any packets through at all, but I was on the 5.15 vendor kernel.  Hrm

(visionfive2 btw)

**Comment by NickCao** [comment]
Haven't tried the vendor kernel yet, I'm (this repo) on kernel 6.2, with not yet upstreamed patches applied.

**Comment by kangaroo** [comment]
Closing as your latest push fixes ethernet.
