### ISSUE TITLE
Add Readme and instructions to create sd card images

### ISSUE THREAD

**Issue by 6543** [NickCao/nixos-riscv#4]

**Comment by requaos** [comment]
+1 for visionfive2 specifics

**Comment by NickCao** [comment]
Added in https://github.com/NickCao/nixos-riscv/commit/c73d9b015cac4acb7d449e0e6b9d4da8f78f35ba, feel free to ask for more information to be included.

**Comment by 6543** [comment]
that was quick!

thank :rocket:
