### ISSUE TITLE
edk2 build?

### ISSUE THREAD

**Issue by colemickens** [NickCao/nixos-riscv#6]
Hi!

Thanks for this resource.

Just wanted to point this out: [StarFive VisionFive 2 SBC Now Supports TianoCore EDK II (UEFI)](https://forum.rvspace.org/t/unlocking-new-possibilities-starfive-visionfive-2-sbc-now-supports-tianocore-edk-ii-uefi/2779) ([rvspace.org](https://news.ycombinator.com/from?site=rvspace.org))

I'm not sure how hard it would be to use nixpkgs's edk2 infra to build this, but I thought you might find it interesting, or worth packaging.

**Comment by NickCao** [comment]
Does this mean we can finally have some form of generic image for riscv boards? I would love to investigate this!

**Comment by colemickens** [comment]
I *think* so? Assuming a board-specific EDKII build in the SPI? And with my tired brain unsure of how DTBs work with EDKII...

Though, in theory, u-boot's UEFI support should/could provide something similar.... but u-boot is it's own thing, which I'm sure you know better than I, since it seems like you're maintaining a VF2 u-boot fork also...

It seems like nixpkgs doesn't have support for riscv64-linux, and I don't know EDKII or it's build tools/system, which is partially while I filed this rather than tinkering with it more myself. But I guess if there's a riscv64 board port, there must exist some build and hopefully cross build support in some tree.

**Comment by NickCao** [comment]
Got a working build in https://github.com/NickCao/nixos-riscv/blob/73e1d5c391ad93c52be828cdd0a7fc3ec3169bf5/edk2-vf2.nix
