### ISSUE TITLE
question: visionfive2 generate "visionfive2_fw_payload.img"

### ISSUE THREAD

**Issue by colemickens** [NickCao/nixos-riscv#7]
Does it make sense to have the u-boot visionfive2 package generate and output the `visionfive2_fw_payload.img` file?

This is what the user guide uses for upgrading u-boot in place, which is my goal.

**Comment by colemickens** [comment]
I guess this would need opensbi too.

**Comment by NickCao** [comment]
It's easier to boot from sdcard (with u-boot in it), than installing u-boot into SPI flash. Nonetheless, we can provide that img, if users do need it.

**Comment by NickCao** [comment]
Just noticed that visionfive2  is already upstreamed to nixos-hardware: https://github.com/NixOS/nixos-hardware/blob/master/starfive/visionfive/v2/firmware.nix

**Comment by colemickens** [comment]
Oh how excellent, glad to know that, too. Thanks!

**Comment by colemickens** [comment]
Sorry to be nosy/noisy, but do you not use this then? https://github.com/NickCao/u-boot-starfive

**Comment by NickCao** [comment]
It was upstream uboot with starfive patches applied, but now as the first batch of the patches has been merged, there's no difference between this fork and the upstream.
