### ISSUE TITLE
nixos-hardware: switch to u-boot upstream

### ISSUE THREAD

**Issue by colemickens** [NickCao/nixos-riscv#8]
I noticed you forked `nixos-hardware`. I am curious if you're trying to build the july RC of u-boot for starfive2? I would prefer to use it over the starfive fork. Figured I'd ask instead of potentially duplicating efforts.

It seems like the build process around the opensbi/dynamic_fw.img is a bit changed, I haven't quite gotten it all building yet.

**Comment by NickCao** [comment]
Switching would make use lose some functionalities, namely ethernet and nvme support, which is yet to be merged: https://rvspace.org/en/project/JH7110_Upstream_Plan#u-boot

**Comment by 6543** [comment]
@NickCao merged at 2023.10-rc3 🎉

**Comment by NickCao** [comment]
> @NickCao merged at 2023.10-rc3 🎉

The build fails with `make[2]: *** No rule to make target 'arch/riscv/dts/jh7110-starfive-visionfive-2.dtb', needed by 'dtbs'.  Stop.`

**Comment by NickCao** [comment]
Narrowed the issue to https://github.com/NixOS/nixpkgs/pull/277997, now we can try again.

**Comment by NickCao** [comment]
Implemented in https://github.com/NixOS/nixos-hardware/pull/819
